### ISSUE TITLE
unable to rotate image?

### ISSUE THREAD

**Issue by teras** [treeform/flippy#12]
Hello!

I am trying to do a test rotation on an image.
I am using this code
```nim
var test = newImage(50,50,4)
discard test.rotate(2)
```
but it fails with the following error message:
```
/Users/teras/Works/Development/Nim/emailform/emailform.nim(7) emailform
/Users/teras/.nimble/pkgs/flippy-0.4.1/flippy.nim(684) rotate
/Users/teras/.nimble/pkgs/flippy-0.4.1/flippy.nim(578) getSubImage
/Users/teras/.nimble/pkgs/flippy-0.4.1/flippy.nim(159) getRgba
/Users/teras/.choosenim/toolchains/nim-1.0.6/lib/system/assertions.nim(27) failedAssertImpl
/Users/teras/.choosenim/toolchains/nim-1.0.6/lib/system/assertions.nim(20) raiseAssert
/Users/teras/.choosenim/toolchains/nim-1.0.6/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: /Users/teras/.nimble/pkgs/flippy-0.4.1/flippy.nim(159, 10) `y >= 0 and y < image.height`  [AssertionError]
```

Am I using it wrong?

**Comment by teras** [comment]
I added before line 684 in flippy.nim the following code to debug it:
```nim
  echo $result & " -- " , 1+int((result.width - newWidth)/2) , " " , 1+int((result.height - newHeight)/2) , " " , newWidth , "/" , newHeight
```
I found that the problem is indeed with out of bounds numbers and the result is
`<Image 50x51:4> -- 1 1 51/51`
different values, I even have negative numbers, like for
```nim
var image = newImage(500,50,4)
echo image.rotate(20)
```
I get negative results 
```<Image 547x223:4> -- 166 -130 217/486```  

Should this happen?

**Comment by treeform** [comment]
There seems to be a bug with the rotate method. @benjif could you take a look?

**Comment by treeform** [comment]
Oh I have figured it out. It was trimming the image incorrectly. I created a better trim function and will now use that.

https://github.com/treeform/flippy/commit/0c1a9f911d7ce83785e944387d92d3924339c377

Also added a test case for your error.

Thank you for reporting the bug!

**Comment by teras** [comment]
Please excuse my comment.
I think the trim function is wrong.
It is good as a generic method, but not in this case.
What if an image is mostly "transparent", but only the center is painted?
Then rotation will minimize the image instead, not just rotate it.

IMHO the four edges of the rotated box should be calculated and crop the image accordingly.
Do you think we should discuss it more?

**Comment by treeform** [comment]
Yeah you are probably right. I did not think about this case.

**Comment by teras** [comment]
Maybe take into account something like this
https://gamedev.stackexchange.com/questions/86755/how-to-calculate-corner-positions-marks-of-a-rotated-tilted-rectangle

Find the location of the four points 
- (x,y)
- (x+width, y)
- (x+width,y+height)
- (x,y+height)

and keep the min/max X and min/max Y as bounding box of the clipped area

**Comment by treeform** [comment]
Yes you are right. I will take a look.

**Comment by treeform** [comment]
I thing it was fixed by @guzba https://github.com/treeform/flippy/pull/16
