### ISSUE TITLE
Resizing Images using -d:useStl giving strange results

### ISSUE THREAD

**Issue by faulander** [treeform/flippy#14]
I have a test image:
![image](https://user-images.githubusercontent.com/38588197/79005167-970f7d00-7b56-11ea-9936-9d288a4a81a4.png)
as you can see, it's roughly 10mb big and has a resolution 10315y7049

if i run the following code, it results in that image:
```
     var image = loadImage(file)
      if image.width > maxWidth or image.height > maxHeight:
        var height = cast[float64](image.height)
        var width = cast[float64](image.width)
        var finalHeight, finalWidth: int
        #echo "Resolution old ", image.height, "x", image.width
        var vh = cast[float64](height / width)
        #echo "VH: ", vh
        if height >= width:
          finalHeight = cast[int](maxHeight)
          finalWidth = cast[int](width / vh)
        else:
          finalWidth = cast[int](maxWidth)
          finalHeight = cast[int](height * vh)
        #echo "Resolution:", image.height, "x", image.width, "-->", finalHeight, "x", finalWidth
        image.height = finalHeight
        image.width = finalWidth  
        image.save(file)
```
The resulting image has a size of 40MB and looks like this:
![image](https://user-images.githubusercontent.com/38588197/79005422-1d2bc380-7b57-11ea-89a7-f9f163ec3bfc.png)

**Comment by treeform** [comment]
Sorry I don't have a resize function.

Setting the width and height of the image will not resize it. It just make the .data be in wrong format.

**Comment by treeform** [comment]
I have added a `resize(w, h)` proc.

Take a looK:
https://github.com/treeform/flippy/blob/841a0913a72a884f850055d605061575e413ba87/tests/flippytest.nim#L178
