### ISSUE TITLE
Flippy is not loading an image

### ISSUE THREAD

**Issue by Zed-Bailey** [treeform/flippy#25]
When trying to load an image into flippy i'm getting `illegal storage access errors` and a `signature mismatch` error as well
Error seems to originate at line 106 where it is assigning the image width from `png.width` to `result.width`

flippy version: 0.4.5
os: OSX

the code to load in an image: `var mainImage: Image = loadImage(imagepath)`
Full error below
```
signature mismatch
Traceback (most recent call last)
/Users/__/Projects/Code/imgToGif/src/splitTga.nim(58) splitTga
/Users/__/Projects/Code/imgToGif/src/splitTga.nim(8) splitTgaToPng
/Users/__/.nimble/pkgs/flippy-0.4.5/flippy.nim(106) loadImage
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by treeform** [comment]
Do you have an image you are trying to load?

**Comment by Zed-Bailey** [comment]
yes im trying to load in the attached image
[clouds](https://user-images.githubusercontent.com/40908679/87897194-e5091a80-ca8d-11ea-85b1-c42627780563.png)

edit: hmm image doesn't seem to be loading, [im using cloud 1 from here](https://blogs.unity3d.com/2016/11/28/free-vfx-image-sequences-flipbooks/) and converting it to png

**Comment by treeform** [comment]
Your image appears to be invalid? Maybe error during conversion?

**Comment by treeform** [comment]
Its not a PNG image, its some sort of raw image maybe?

![image](https://user-images.githubusercontent.com/125948/87902060-7be1c280-ca0d-11ea-8736-49970f14d6c0.png)

**Comment by Zed-Bailey** [comment]
hmmm...I'm not exactly sure that makes no sense to me :), i've tried saving pictures in .png format directly and it's still failing?
[this line in my code seems to be where the problems are stemming from](https://github.com/Zed-Inc/imgToGif/blob/d538f9a8786acad333c87997d2d50152ff9f64cb/src/imgToGif.nim#L153) which again is just the loadImage() proc

**Comment by treeform** [comment]
If you can send me more of the images that are failing to work I can try to see why.

But if they are like your first image... they are just not PNG images, they have .png extension but inside they are not PNGs at all.

As a side note what you are trying to do can be easily done with image magic:
```
convert   -delay 20   -loop 0   sphere*.png animatespheres.gif
```
https://www.tjhsst.edu/~dhyatt/supercomp/n401a.html

**Comment by treeform** [comment]
Closing due to no responses. I think solution was reached. Image was bad.
