### ISSUE TITLE
Artifacts introduced when rendering subpixels

### ISSUE THREAD

**Issue by possdog** [treeform/flippy#27]
When any element lands on a subpixel (any non-integer or non-`.0` float), rendering artifacts will be introduced.
![example 1](https://user-images.githubusercontent.com/54759062/92011845-4836cf80-ed11-11ea-9265-addbcf7a46a2.gif) ![example 2](https://cdn.discordapp.com/attachments/692619607961239622/750753092848582706/spinner.gif)
![example 3](https://cdn.discordapp.com/attachments/692619607961239622/750751757520338954/unknown.png) ![example 4](https://cdn.discordapp.com/attachments/692619607961239622/748586755040739508/unknown.png)

Tested on both size, position, and corner radius (in Fidget).

**Comment by treeform** [comment]
I think I will phase out the current pixel based versions of these and focus on the vector paths versions of these.

New API is more like canvas or cairo:
```nim
proc roundRect(path: Path, x, y, w, h, nw, ne, se, sw: float32) =
  ## Draw a round rectangle with different radius corners.
  path.moveTo(x+nw, y)
  path.arcTo(x+w, y,   x+w, y+h, ne)
  path.arcTo(x+w, y+h, x,   y+h, se)
  path.arcTo(x,   y+h, x,   y,   sw)
  path.arcTo(x,   y,   x+w, y,   nw)
  path.closePath()
```

**Comment by treeform** [comment]
Flippy is not longer developed, all development has moved to [pixie](https://github.com/treeform/pixie). 

Pixie can draw this and all other kinds of paths correctly.
