### ISSUE TITLE
Can pictures be saved as memory files? 

### ISSUE THREAD

**Issue by lihf8515** [treeform/flippy#28]
Can pictures be saved as memory files? I don't want to generate on disk because I generated temporary files

**Comment by treeform** [comment]
Not sure what you mean?
* Do you want to write to like a RAM disk?
* Do you want to get the byte data?
* Do you want to get the byte data after it was compressed as a PNG?

**Comment by treeform** [comment]
Sorry I don't understand what you mean. Feel free to reopen when a better explanation.

**Comment by lihf8515** [comment]
What I mean is that I generate a Picture, which is not stored on the local disk, but stored in memory, and then returned to the Web for display by the Web client. The existing 'image.save()' method can only be saved on a local disk.
