### ISSUE TITLE
Getting an error when running the basic usage example: Error: undeclared identifier: 'rgba'

### ISSUE THREAD

**Issue by james-guevara** [treeform/flippy#29]
Hi, thank you for writing this library. I tried compiling the basic example:

```
import flippy
# load an image
var image = loadImage("tests/lenna.png")
# print it out
echo image
# get a color pixel
echo image.getRgba(100, 100)
# put a color pixel
image.putRgba(10, 10, rgba(255, 0, 0, 255))
# blit a rectangular part from one place to another
blit(image, image, rect(0, 0, 100, 100), rect(100, 100, 100, 100))
# draw a line
image.line(vec2(11, 11), vec2(100, 100), rgba(0, 0, 0, 255))
# minify image by 2 or 1/2 or scale by 50%
image = image.minify(2)
# save the image to a file
image.save("tests/lenna2.png")
```

I use `nim c flippy_test.nim` and this is the output:

```
Hint: used config file '/Users/owner/.choosenim/toolchains/nim-1.4.0/config/nim.cfg' [Conf]
Hint: used config file '/Users/owner/.choosenim/toolchains/nim-1.4.0/config/config.nims' [Conf]
......................................
/Users/owner/nim/flippy/flippy_test.nim(9, 23) Error: undeclared identifier: 'rgba'

```

My OS is macOS Catalina Version 10.15.6. I'm using Nim Compiler Version 1.4.0 [MacOSX: amd64]. 

I'm new to Nim, so perhaps I'm missing something pretty obvious... (having to do with the wrappers for the C image libraries being used or something like that? Really don't know. 😅) Also, it compiles if I take out the lines that use rgba, vec2, and rect parameters.

**Comment by james-guevara** [comment]
I got it to work actually. Just had to import chroma and vmath as well. (Though the flippy library itself imports these other two libraries so I'm not sure if I also should have to import them in this code..)

**Comment by treeform** [comment]
Thanks! I have added the imports to the example.
