### ISSUE TITLE
The 'image.save()' method can only be saved on a local disk. Can it be saved in memory?

### ISSUE THREAD

**Issue by lihf8515** [treeform/flippy#31]
What I mean is that I generate a Picture, which is not stored on the local disk, but stored in memory, and then returned to the Web for display by the Web client. The existing 'image.save()' method can only be saved on a local disk.

_Originally posted by @lihf8515 in https://github.com/treeform/flippy/issues/28#issuecomment-727470455_

**Comment by treeform** [comment]
Flippy is not longer developed, all development has moved to [pixie](https://github.com/treeform/pixie). 

Pixie's png has encode that can encode to memory.
