### ISSUE TITLE
Unable to build/install other libraries (e.g. NSU) that depends on flippy

### ISSUE THREAD

**Issue by selectptr** [treeform/flippy#36]
There's an issue when trying to install other libraries such as Senketsu/nsu which depends on flippy. According to the error, it seems the issue lies with flippy.nim having an undeclared identifier "Rect". I also tried the latest version of flippy and it produced the same error.

The error I am getting is
**/root/.nimble/pkgs/flippy-0.4.0/flippy.nim(206, 58) Error: undeclared identifier: 'Rect'**
       Tip: 16 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: nsu
        ... Execution failed with exit code 1
        ... Command: /home/user/Desktop/nim-1.4.8/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.1.5 --path:/root/.nimble/pkgs/x11-1.1 --path:/root/.nimble/pkgs/winim-3.6.1 --path:/root/.nimble/pkgs/flippy-0.4.0 --path:/root/.nimble/pkgs/vmath-1.0.8 --path:/root/.nimble/pkgs/chroma-0.2.5 --path:/root/.nimble/pkgs/print-1.0.0 --path:/root/.nimble/pkgs/stb_image-2.5 --hints:off -o:/home/user/Desktop/nsu/nsu /home/user/Desktop/nsu/src/nsu.nim

**Comment by treeform** [comment]
Senketsu/nsu probably needs an older version of Flippy. Rect was moved to the [bumpy](https://github.com/treeform/bumpy) library. Flippy is not longer developed, all development has moved to [pixie](https://github.com/treeform/pixie).

Senketsu/nsu should probably move over to use pixie.
