### ISSUE TITLE
 does not support Unicode filenames on Windows

### ISSUE THREAD

**Issue by EasiestSoft** [treeform/flippy#6]
`can't fopen` exception when loading or saving an image with Unicode characters in the path on Windows

stb_image C library itself supports Unicode filenames on Windows:
https://github.com/nothings/stb/issues/557

**Comment by treeform** [comment]
I have switched to using nimPNG which should support Unicode files names. Please try it.

**Comment by treeform** [comment]
https://github.com/treeform/flippy/commit/481d9349b439456b6a8ced9e6760b4bf385d332a

**Comment by EasiestSoft** [comment]
Sorry for the delay. tested, now it supports Unicode file names on Windows
