### ISSUE TITLE
image.putRgba issue or user error ?

### ISSUE THREAD

**Issue by melMass** [treeform/flippy#7]
Hi,

Trying this simple test does not seem to work on OSX, Am I using it wrong 🙈 ?

```nim
import flippy, chroma

const w = 128
const h = 128

proc flipTest*() = 
  var image = newImage(w,h,4)
  for x in {0..w-1}:
    for y in {0..h-1}:
      if x < int(w/2):
        image.putRgba(x, y, rgba(255, 0, 0, 255))
      else:
        image.putRgba(x, y, rgba(0, 0, 255, 255))
  image.save("test.png")
```
![image](https://user-images.githubusercontent.com/7041726/75613344-bca77080-5b2c-11ea-9f59-565c1d306c0d.png)

**Comment by melMass** [comment]
Removing `--gc:arc ` solves the issue

![image](https://user-images.githubusercontent.com/7041726/75613504-c3cf7e00-5b2e-11ea-86f9-d164fa539273.png)

**Comment by treeform** [comment]
Sorry I have not worked on --gc:arc support yet. I am waiting for it to mature more.

**Comment by treeform** [comment]
I have looked into this again. NimPNG does not have arc support, but if you install stb_image and use that with `-d:useStb` flag it works:

```
nim c -r --gc:arc -d:useStb "c:\p\flippy\tests\flippytest.nim"
```

Maybe use this as a work around for now?

See: https://github.com/jangko/nimPNG/issues/37

**Comment by treeform** [comment]
This has been fixed thank you for reporting it!
